version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: jira_postgres
    environment:
      POSTGRES_USER: jirauser
      POSTGRES_PASSWORD: jirapassword
      POSTGRES_DB: jiradb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - jira_network

  jira:
    image: atlassian/jira-software:8.20.0
    container_name: jira_server
    environment:
      - ATL_JDBC_URL=jdbc:postgresql://postgres:5432/jiradb
      - ATL_JDBC_USER=jirauser
      - ATL_JDBC_PASSWORD=jirapassword
      - ATL_JIRA_HOME=/var/atlassian/application-data/jira
    ports:
      - "8080:8080"
    volumes:
      - jira_data:/var/atlassian/application-data/jira
    depends_on:
      - postgres
    networks:
      - jira_network

volumes:
  postgres_data:
    driver: local
  jira_data:
    driver: local

networks:
  jira_network:
    driver: bridge
